services:
  - name: dhxrshxn-fastapi-project-backend
    type: web
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dhxrshxn-db
          property: connectionString
      - key: PYTHON_PATH
        value: /usr/local/bin/python3

databases:
  - name: dhxrshxn-db
    region: oregon
    plan: free
    diskSizeGB: 1